In [3]:
pip install osa

Defaulting to user installation because normal site-packages is not writeable
Collecting osa
  Using cached osa-0.2.3-py3-none-any.whl (25 kB)
Installing collected packages: osa
Successfully installed osa-0.2.3
Note: you may need to restart the kernel to use updated packages.

In [4]:
# Get libraries
import pandas as pd
import osa
from astropy.time import Time
import astropy.units as u
from astropy.coordinates import get_sun, AltAz, EarthLocation

In [5]:
theday = '2019-10-18'
outputdaysyntax = '10_18_2019'
#theday = arcpy.GetParameterAsText(0)
#if arcpy.Exists(theday):
#    print("Using day input")
#else: 
#    theday = '2019-05-29'
#    print("Using test day input")

originalroad = r".\SampleRoads.gdb\Street_Centerlines"
    
    
#originalroad = arcpy.GetParameterAsText(1)
#if arcpy.Exists(originalroad):
#    print("Using road input")
#else: 
#    originalroad = r"C:\Stories\glareanalysis\glare1\SampleRoads.gdb\Street_Centerlines_small"
#    print("Using test road input")   
 
terrain = r".\Terrain.tif"

#terrain = arcpy.GetParameterAsText(2)    
#if arcpy.Exists(terrain):
#    print("Using terrain input")
#else: 
#    terrain = r"C:\Stories\glareanalysis\glare1\Terrain2m_fallschurch.tif"
#    print("Using test terrain input")  




#########

# PART I USER INPUTS - SUN Times to examine and general sun location coordinate for entire study area


# Sun time/location inputs use a table of data for the times of day of SUN TABLE INPUTS

# input the day of the year we are examining, and the general centerpoint of the location area
#theday = '2019-05-29'
coor_lat = 38.86755435
coor_long = -77.16801577
grid_id = '29'  # just an identifier for the name of a grid cell, this is not used in any calculations
                # think of this as a national grid id maybe    

sunhorizontalangle_filter1 = 18 # max angle of sun to consider for calculation (
                #this is befire we factor in the rd angle, think of this as a filter)

#look at these 5 min intervals in morning and afternoon hours
myhours = ['05','06','07','08','09','18','19','20','21','22']
myminutes = ['00','05','10','15','20','25','30','35','40','45','50','55']

In [14]:
#######

#PART 2 USER INPUTS - Road Featureclass and terrain inputs

# USER INPUTS - ALL PASTED TO TOP existing inputs
#originalroad = r"C:\Stories\glareanalysis\glare1\SampleRoads.gdb\Street_Centerlines"
#terrain = r"C:\Stories\glareanalysis\glare1\Terrain_fallschurch.tif"

import json
import os
import sys
from qgis.core import QgsProject, QgsVectorLayer, QgsProcessingFeatureSourceDefinition, QgsFeatureRequest, QgsVectorFileWriter, QgsApplication, QgsProcessingProvider
from qgis.analysis import QgsNativeAlgorithms
import matplotlib.pyplot as plt

os.environ["QT_QPA_PLATFORM"] = "offscreen" # Esta l√≠nea es necesaria para poder iniciar una instancia QgsApplication(), en caso de que sea necesario

QgsApplication.setPrefixPath(None, True)

import processing
from processing.core.Processing import Processing

# Inicia algoritmos
Processing.initialize()

# establece directorio de trabajo
#os.chdir('/home/studio-lab-user/sagemaker-studiolab-notebooks/intro_pyqgis')

proyecto = QgsProject.instance()


######

# PART 4 USER INPUTS - FILTERED ANGLES to find the areas where the sun in your face when driving

SunDelta_HorizontalAngle_Max = 8
SunDelta_VerticalAngle_Max = 8

#name of final output filtered featureclass
output_roadsfc_calc = "glare_on_" + outputdaysyntax

# End User inputs

In [ ]:
originalroad

In [15]:
########originalroad###########


# PART I - CREATE SUN DATAFRAME TABLE (non geospatial stuff)

# uses astropy to find sun angles at a given place and several times in the morning and afternoon

# ["sun_id", "FullDayTimeText", "SolarAzimuth", "SolarElevation", "X", "Y", "GridID" ]

print (r"Creating sun table ...")

Creating sun table ...

In [16]:
# construct/create an array of the datetimestrings to examine and add as a column
mydaytime = []

for aa in range(len(myhours)):
    for bb in range(len(myminutes)):
        date_time_str = theday + ' ' + myhours[aa] + ':' + myminutes[bb] 
        mydaytime.append(date_time_str)

mydaytime

['2019-10-18 05:00',
 '2019-10-18 05:05',
 '2019-10-18 05:10',
 '2019-10-18 05:15',
 '2019-10-18 05:20',
 '2019-10-18 05:25',
 '2019-10-18 05:30',
 '2019-10-18 05:35',
 '2019-10-18 05:40',
 '2019-10-18 05:45',
 '2019-10-18 05:50',
 '2019-10-18 05:55',
 '2019-10-18 06:00',
 '2019-10-18 06:05',
 '2019-10-18 06:10',
 '2019-10-18 06:15',
 '2019-10-18 06:20',
 '2019-10-18 06:25',
 '2019-10-18 06:30',
 '2019-10-18 06:35',
 '2019-10-18 06:40',
 '2019-10-18 06:45',
 '2019-10-18 06:50',
 '2019-10-18 06:55',
 '2019-10-18 07:00',
 '2019-10-18 07:05',
 '2019-10-18 07:10',
 '2019-10-18 07:15',
 '2019-10-18 07:20',
 '2019-10-18 07:25',
 '2019-10-18 07:30',
 '2019-10-18 07:35',
 '2019-10-18 07:40',
 '2019-10-18 07:45',
 '2019-10-18 07:50',
 '2019-10-18 07:55',
 '2019-10-18 08:00',
 '2019-10-18 08:05',
 '2019-10-18 08:10',
 '2019-10-18 08:15',
 '2019-10-18 08:20',
 '2019-10-18 08:25',
 '2019-10-18 08:30',
 '2019-10-18 08:35',
 '2019-10-18 08:40',
 '2019-10-18 08:45',
 '2019-10-18 08:50',
 '2019-10-18 08:55',
 '2019-10-18 09:00',
 '2019-10-18 09:05',
 '2019-10-18 09:10',
 '2019-10-18 09:15',
 '2019-10-18 09:20',
 '2019-10-18 09:25',
 '2019-10-18 09:30',
 '2019-10-18 09:35',
 '2019-10-18 09:40',
 '2019-10-18 09:45',
 '2019-10-18 09:50',
 '2019-10-18 09:55',
 '2019-10-18 18:00',
 '2019-10-18 18:05',
 '2019-10-18 18:10',
 '2019-10-18 18:15',
 '2019-10-18 18:20',
 '2019-10-18 18:25',
 '2019-10-18 18:30',
 '2019-10-18 18:35',
 '2019-10-18 18:40',
 '2019-10-18 18:45',
 '2019-10-18 18:50',
 '2019-10-18 18:55',
 '2019-10-18 19:00',
 '2019-10-18 19:05',
 '2019-10-18 19:10',
 '2019-10-18 19:15',
 '2019-10-18 19:20',
 '2019-10-18 19:25',
 '2019-10-18 19:30',
 '2019-10-18 19:35',
 '2019-10-18 19:40',
 '2019-10-18 19:45',
 '2019-10-18 19:50',
 '2019-10-18 19:55',
 '2019-10-18 20:00',
 '2019-10-18 20:05',
 '2019-10-18 20:10',
 '2019-10-18 20:15',
 '2019-10-18 20:20',
 '2019-10-18 20:25',
 '2019-10-18 20:30',
 '2019-10-18 20:35',
 '2019-10-18 20:40',
 '2019-10-18 20:45',
 '2019-10-18 20:50',
 '2019-10-18 20:55',
 '2019-10-18 21:00',
 '2019-10-18 21:05',
 '2019-10-18 21:10',
 '2019-10-18 21:15',
 '2019-10-18 21:20',
 '2019-10-18 21:25',
 '2019-10-18 21:30',
 '2019-10-18 21:35',
 '2019-10-18 21:40',
 '2019-10-18 21:45',
 '2019-10-18 21:50',
 '2019-10-18 21:55',
 '2019-10-18 22:00',
 '2019-10-18 22:05',
 '2019-10-18 22:10',
 '2019-10-18 22:15',
 '2019-10-18 22:20',
 '2019-10-18 22:25',
 '2019-10-18 22:30',
 '2019-10-18 22:35',
 '2019-10-18 22:40',
 '2019-10-18 22:45',
 '2019-10-18 22:50',
 '2019-10-18 22:55']

In [17]:
#create the sun table dataframe
#from https://chrisalbon.com/python/data_wrangling/pandas_create_column_with_loop/

#suntablefields = ["sun_id","FullDayTimeText", "SolarAzimuth", "SolarElevation", "X", "Y", "GridID" ]

raw_data = {'FullDayTimeText': mydaytime }
sun_df = pd.DataFrame(raw_data, columns = ['FullDayTimeText'])

#add these hard coded fields to all rows so we persist this through ti the final FC 
# in case someone cares to use different sunposisitons in the same calcuation and wants to know
#what rpows used which sun position and or reference grid ID, such as the national 1 km grid
sun_df['X'] = coor_long
sun_df['Y'] = coor_lat
sun_df['GridID'] = grid_id

#re our date is a date tupe field and 
# http://strftime.org/
sun_df['FullDayTimeText'] = pd.to_datetime(sun_df['FullDayTimeText'], format="%Y-%m-%d %H:%M")
sun_df = sun_df.astype({'GridID': int})

sun_df

#sun_df.dtypes

        FullDayTimeText          X          Y  GridID
0   2019-10-18 05:00:00 -77.168016  38.867554      29
1   2019-10-18 05:05:00 -77.168016  38.867554      29
2   2019-10-18 05:10:00 -77.168016  38.867554      29
3   2019-10-18 05:15:00 -77.168016  38.867554      29
4   2019-10-18 05:20:00 -77.168016  38.867554      29
..                  ...        ...        ...     ...
115 2019-10-18 22:35:00 -77.168016  38.867554      29
116 2019-10-18 22:40:00 -77.168016  38.867554      29
117 2019-10-18 22:45:00 -77.168016  38.867554      29
118 2019-10-18 22:50:00 -77.168016  38.867554      29
119 2019-10-18 22:55:00 -77.168016  38.867554      29

[120 rows x 4 columns]

In [18]:
#Calcuate solar elevation field and add it

def CalcSolarElevation(x,y,tt):
    
  # if you get a value error
  #ValueError: interpolating from IERS_Auto using predictive values that are more
  #than 30.0 days old.

    #Normally you should not see this error because this class
    #automatically downloads the latest IERS-A table.  Perhaps you are
    #offline?  If you understand what you are doing then this error can be
    #suppressed by setting the auto_max_age configuration variable to
    #``None``:

  #from astropy.utils.iers import conf
  #conf.auto_max_age = None

    
      
  utcoffset = -4*u.hour  # Eastern Daylight Time  
  sun_time = Time(tt) - utcoffset  #UTC time
  loc = EarthLocation(lon = x * u.deg, lat = y * u.deg)
  altaz = AltAz(obstime=sun_time, location=loc)
  altangle = get_sun(sun_time).transform_to(altaz).alt 
  return altangle.degree

#this works because we loop and get the value out - it is slow though
for i in sun_df.index:
    sun_df.at[i, 'SolarElevation'] = CalcSolarElevation(sun_df.at[i,'X'], 
                                                        sun_df.at[i, 'Y'], 
                                                        sun_df.at[i, 'FullDayTimeText'])
sun_df

        FullDayTimeText          X          Y  GridID  SolarElevation
0   2019-10-18 05:00:00 -77.168016  38.867554      29      -28.052322
1   2019-10-18 05:05:00 -77.168016  38.867554      29      -27.095696
2   2019-10-18 05:10:00 -77.168016  38.867554      29      -26.136509
3   2019-10-18 05:15:00 -77.168016  38.867554      29      -25.175010
4   2019-10-18 05:20:00 -77.168016  38.867554      29      -24.211440
..                  ...        ...        ...     ...             ...
115 2019-10-18 22:35:00 -77.168016  38.867554      29      -47.557996
116 2019-10-18 22:40:00 -77.168016  38.867554      29      -48.361025
117 2019-10-18 22:45:00 -77.168016  38.867554      29      -49.150208
118 2019-10-18 22:50:00 -77.168016  38.867554      29      -49.924645
119 2019-10-18 22:55:00 -77.168016  38.867554      29      -50.683389

[120 rows x 5 columns]

In [21]:
# calc solar azimuth

def CalcSolarAzimuth(x,y,tt):
    
  utcoffset = -4*u.hour  # Eastern Daylight Time  
  sun_time = Time(tt) - utcoffset  #UTC time
  loc = EarthLocation(lon = x * u.deg, lat = y * u.deg)
  altaz = AltAz(obstime=sun_time, location=loc)
  azangle = get_sun(sun_time).transform_to(altaz).az
  return azangle.degree

#df['SolarAzimuth'] = CalcSolarAzimuth(df['X'], df['Y'], df['FullDayTimeText'])
for i in sun_df.index:
    sun_df.at[i, 'SolarAzimuth'] = CalcSolarAzimuth(sun_df.at[i,'X'], 
                                                    sun_df.at[i, 'Y'], 
                                                    sun_df.at[i, 'FullDayTimeText'])

sun_df
#sun_df.dtypes

,FullDayTimeText,X,Y,GridID,SolarElevation,sun_id,SolarAzimuth
30,2019-10-18 07:30:00,-77.168016,38.867554,29,0.908828,1,103.121724
31,2019-10-18 07:35:00,-77.168016,38.867554,29,1.854430,2,103.912719
32,2019-10-18 07:40:00,-77.168016,38.867554,29,2.796789,3,104.707996
33,2019-10-18 07:45:00,-77.168016,38.867554,29,3.735704,4,105.507978
34,2019-10-18 07:50:00,-77.168016,38.867554,29,4.670970,5,106.313091
35,2019-10-18 07:55:00,-77.168016,38.867554,29,5.602376,6,107.123761
36,2019-10-18 08:00:00,-77.168016,38.867554,29,6.529709,7,107.940419
37,2019-10-18 08:05:00,-77.168016,38.867554,29,7.452746,8,108.763497
38,2019-10-18 08:10:00,-77.168016,38.867554,29,8.371262,9,109.593430
39,2019-10-18 08:15:00,-77.168016,38.867554,29,9.285025,10,110.430657
40,2019-10-18 08:20:00,-77.168016,38.867554,29,10.193794,11,111.275620
41,2019-10-18 08:25:00,-77.168016,38.867554,29,11.097324,12,112.128764
42,2019-10-18 08:30:00,-77.168016,38.867554,29,11.995361,13,112.990540
43,2019-10-18 08:35:00,-77.168016,38.867554,29,12.887644,14,113.861400
44,2019-10-18 08:40:00,-77.168016,38.867554,29,13.773903,15,114.741802
45,2019-10-18 08:45:00,-77.168016,38.867554,29,14.653860,16,115.632208
46,2019-10-18 08:50:00,-77.168016,38.867554,29,15.527228,17,116.533082
47,2019-10-18 08:55:00,-77.168016,38.867554,29,16.393712,18,117.444892
48,2019-10-18 09:00:00,-77.168016,38.867554,29,17.253004,19,118.368111
60,2019-10-18 18:00:00,-77.168016,38.867554,29,4.129416,20,253.950283
61,2019-10-18 18:05:00,-77.168016,38.867554,29,3.191308,21,254.750661
62,2019-10-18 18:10:00,-77.168016,38.867554,29,2.249640,22,255.546094
63,2019-10-18 18:15:00,-77.168016,38.867554,29,1.304613,23,256.337004
64,2019-10-18 18:20:00,-77.168016,38.867554,29,0.356425,24,257.123813

In [22]:
# test to show all rows
import IPython.display

IPython.display.HTML(sun_df.to_html())

In [23]:
#only keep rows where the elevation angle is less than than the max angle
sun_df = sun_df[sun_df.SolarElevation <= sunhorizontalangle_filter1] #this is currenlty 18, set above, before the road filter

#only keep rows above zero
sun_df = sun_df[sun_df.SolarElevation > 0 ]

#sun_df

In [20]:
#create list of sun-ids to add as a column from 1 - length

sun_df['sun_id'] = range(1,1+len(sun_df))

sun_df

#print (r"... created sun table ok. ")

       FullDayTimeText          X          Y  GridID  SolarElevation  sun_id
30 2019-10-18 07:30:00 -77.168016  38.867554      29        0.908828       1
31 2019-10-18 07:35:00 -77.168016  38.867554      29        1.854430       2
32 2019-10-18 07:40:00 -77.168016  38.867554      29        2.796789       3
33 2019-10-18 07:45:00 -77.168016  38.867554      29        3.735704       4
34 2019-10-18 07:50:00 -77.168016  38.867554      29        4.670970       5
35 2019-10-18 07:55:00 -77.168016  38.867554      29        5.602376       6
36 2019-10-18 08:00:00 -77.168016  38.867554      29        6.529709       7
37 2019-10-18 08:05:00 -77.168016  38.867554      29        7.452746       8
38 2019-10-18 08:10:00 -77.168016  38.867554      29        8.371262       9
39 2019-10-18 08:15:00 -77.168016  38.867554      29        9.285025      10
40 2019-10-18 08:20:00 -77.168016  38.867554      29       10.193794      11
41 2019-10-18 08:25:00 -77.168016  38.867554      29       11.097324      12
42 2019-10-18 08:30:00 -77.168016  38.867554      29       11.995361      13
43 2019-10-18 08:35:00 -77.168016  38.867554      29       12.887644      14
44 2019-10-18 08:40:00 -77.168016  38.867554      29       13.773903      15
45 2019-10-18 08:45:00 -77.168016  38.867554      29       14.653860      16
46 2019-10-18 08:50:00 -77.168016  38.867554      29       15.527228      17
47 2019-10-18 08:55:00 -77.168016  38.867554      29       16.393712      18
48 2019-10-18 09:00:00 -77.168016  38.867554      29       17.253004      19
60 2019-10-18 18:00:00 -77.168016  38.867554      29        4.129416      20
61 2019-10-18 18:05:00 -77.168016  38.867554      29        3.191308      21
62 2019-10-18 18:10:00 -77.168016  38.867554      29        2.249640      22
63 2019-10-18 18:15:00 -77.168016  38.867554      29        1.304613      23
64 2019-10-18 18:20:00 -77.168016  38.867554      29        0.356425      24

In [24]:
# END PART I - CREATE SUN DATAFRAME TABLE (non geospatial stuff)

##################################


# PART 2 - This takes the raw roads and then adds the vertices and then 
#         creates the 3d segments with bearing and length attributes


print (r"Creating road segment table ...")

Creating road segment table ...

In [27]:
# USER INPUTS - ALL PASTED TO TOP existing inputs
#originalroad = r"C:\Stories\glareanalysis\glare1\SampleRoads.gdb\Street_Centerlines_small"
#terrain = r"C:\Stories\glareanalysis\glare1\Terrain2m_fallschurch.tif"
#arcpy.env.workspace = r"C:\Stories\glareanalysis\glare1\glare1.gdb"

# Set more environment settings
arcpy.env.outputCoordinateSystem = arcpy.Describe(terrain).spatialReference

#scratch featureclass files that are created on the fly
inputroad = "inputroad"
vertices2d = "vertices2d"
vertices3d = "vertices3d"
simpleline3d = "simpleline3d"
segments3d = "segments3d"

AttributeError: 'str' object has no attribute 'crs'

In [ ]:
# make a working copy from original
arcpy.management.CopyFeatures(originalroad, inputroad)

In [ ]:
#add a field to preserve the objectid as a field
arcpy.management.AddField(inputroad, "RoadID", "LONG")
arcpy.management.CalculateField(inputroad, "RoadID", "!OBJECTID!", "PYTHON3")

In [ ]:

# generalize to remove most vertices
arcpy.edit.Generalize(inputroad, "5 Meters")

In [ ]:


#insert vertices every 200m
#arcpy.edit.Densify(inputroad, "DISTANCE", "200 Meters", "0.33 Feet", 10)
arcpy.edit.Densify(inputroad, "DISTANCE", "200 Meters")

In [ ]:
#make vertices
arcpy.management.FeatureVerticesToPoints(inputroad, vertices2d, "ALL")

In [ ]:
#get the elevation of every vertice
arcpy.ddd.InterpolateShape(terrain, vertices2d, vertices3d, None, 1, "BILINEAR", "DENSIFY", 0, "EXCLUDE")

In [ ]:
#create 3d roads from 3d vertices
arcpy.management.PointsToLine(vertices3d, simpleline3d, "RoadID", None, "NO_CLOSE")

In [ ]:
#create short 3d segments from 3d roads
arcpy.management.SplitLine(simpleline3d, segments3d)

In [ ]:

#add GIS attributes
arcpy.management.AddGeometryAttributes(segments3d, "LENGTH_GEODESIC;LINE_BEARING;LINE_START_MID_END", "METERS")

In [ ]:
print (r"... creating road table ok.")


#  END PART II - CREATE RD SEGMENTS WITH ATTRIBUTES





#############

# PART 3 - CREATE MASTER LARGE PANDAS COMPARISION TABLE 
# -  NOW WORK IN DATAFRAMES WITH OUR RD FC AND COMBINE OUR SUNTABLE To OUR ROADS
# - (NO USER INPUTS)

print (r"Creating large Pandas comparison dataframe ... ")

In [ ]:
#create sdf
roadfc_df = pd.DataFrame.spatial.from_featureclass(segments3d, key=None)

In [ ]:


def findRoadAngle(length_hypotenuse, upper_pt, lower_pt):
    length_opposite = upper_pt - lower_pt
    angleSine = math.degrees(math.sin(length_opposite/length_hypotenuse))
    return angleSine

In [ ]:
#Add the AngleA, AngleB
for i in roadfc_df.index:
    roadfc_df.at[i, 'AngleA'] = findRoadAngle(roadfc_df.at[i,'LENGTH_GEO'], 
                                              roadfc_df.at[i, 'END_Z'], 
                                              roadfc_df.at[i, 'START_Z'])

for i in roadfc_df.index:
    roadfc_df.at[i, 'AngleB'] = findRoadAngle(roadfc_df.at[i,'LENGTH_GEO'], 
                                              roadfc_df.at[i, 'START_Z'], 
                                              roadfc_df.at[i, 'END_Z'])

In [ ]:

# change column name as it is already calculated for BearingA
roadfc_df.rename(columns = {'BEARING':'BearingA'}, inplace = True)

#find BearingB the opposite bearing on a circle from north
def findOppositeBearingeAngle(x):
    a = x + 180
    if a > 360:
        a = a -360
    return a

for i in roadfc_df.index:
    roadfc_df.at[i, 'BearingB'] = findOppositeBearingeAngle(roadfc_df.at[i,'BearingA'])

In [ ]:
roadfc_df

In [ ]:
#create a copy of the table and this will be our target df
#set initial value for a value of  sun id 1
temp_df = roadfc_df.copy()
temp_df['sun_id'] = 1
final_df = temp_df

# now concanenate the same table over and over for sun id 2 to X
for i in range(2, len(sun_df)):
    temp_df = roadfc_df.copy()
    temp_df['sun_id'] = i
        
    final_df = pd.concat([final_df, temp_df])
    
final_df

In [ ]:
# merge sun table to final_df
#from https://chrisalbon.com/python/data_wrangling/pandas_join_merge_dataframe/

finalwithsun_df = pd.merge(final_df, sun_df, on='sun_id')

finalwithsun_df

In [ ]:
# use this function to find the small angle azimuth angle between the sun and road azimuths
# ie, small angle beweek 355 and 5 is 10
# ie, small angle between 175 and 185 is 10
def findsmallangle(x,y):
    a = x - y
    a = (a + 180) % 360 - 180
    return abs(a)

#this finds the sun and road vertical angle difference
#vert_angle = sunangle - roadangle
def findsignedvertanglediff(x,y):
    a = x - y
    return a

In [ ]:

# Create a new column called df.SolarAzimuthDeltaA 
finalwithsun_df['SolarAzimuthDeltaA'] = findsmallangle(finalwithsun_df['BearingA'], finalwithsun_df['SolarAzimuth'])

# Create a new column called df.SolarAzimuthDeltaB
finalwithsun_df['SolarAzimuthDeltaB'] = findsmallangle(finalwithsun_df['BearingB'], finalwithsun_df['SolarAzimuth'])

In [ ]:
# find vert angle difference A
finalwithsun_df['AngleADelta'] =  findsignedvertanglediff(finalwithsun_df['SolarElevation'], finalwithsun_df['AngleA'])


# find vert angle difference B
finalwithsun_df['AngleBDelta'] =  findsignedvertanglediff(finalwithsun_df['SolarElevation'], finalwithsun_df['AngleB'])

In [ ]:
print (r"Number of rows in dataframe = " + str(len(finalwithsun_df)))

In [ ]:
# End PART 3 - CREATE MASTER LARGE PANDAS COMPARISION TABLE 

print (r"Created large pandas dataframe  ok.")

#######################

# PART 4  - FILTER OUT RESULTS

# FILTER OUT ONLY THE GOOOD ROAD SEGMENTS WHERE THE HORIZONTAL AND VERTIVAL ANGLES ARE CLOSE TO THE ALLOWED

In [ ]:
# USer allowed maxes (no negatives allowed for vertical of courser)
#pasted to top of script
#SunDelta_HorizontalAngle_Max = 8
#SunDelta_VerticalAngle_Max = 8

In [ ]:
#HORIZONTAL FILTER

#from https://chrisalbon.com/python/data_wrangling/pandas_selecting_rows_on_conditions/

# Create 2 variables with TRUE for each horizontal angles of the 
# delta (difference between rd and sun) compared to the max allowed if angle is less than allowed offset
#original query in Pro
# SolarAzimuthDeltaA <= %HorizontalSunDelta% Or SolarAzimuthDeltaB <= %HorizontalSunDelta%

GoodSunHorizontalAngleA = finalwithsun_df['SolarAzimuthDeltaA'] <= SunDelta_HorizontalAngle_Max
GoodSunHorizontalAngleB = finalwithsun_df['SolarAzimuthDeltaB'] <= SunDelta_HorizontalAngle_Max

GoodSunHorizontalAngle = GoodSunHorizontalAngleA | GoodSunHorizontalAngleB
#GoodSunHorizontalAngle

In [ ]:
#VERTICAL FILTER

# Create 2 variables with TRUE for each vertical angles of the 
# delta (difference between rd and sun) compared to the max allowed if angle is less than allowed offset

#original query in Pro
# #(AngleADelta <= %VerticalSunDelta% And AngleADelta >= 0) Or (AngleBDelta <= %VerticalSunDelta% And AngleBDelta >= 0)
GoodSunVerticalAngleA_1 = finalwithsun_df['AngleADelta'] <= SunDelta_VerticalAngle_Max
GoodSunVerticalAngleA_2 = finalwithsun_df['AngleADelta'] > 0
GoodSunVerticalAngleA = GoodSunVerticalAngleA_1 & GoodSunVerticalAngleA_2

#GoodSunVerticalAngleA

In [ ]:
GoodSunVerticalAngleB_1 = finalwithsun_df['AngleBDelta'] <= SunDelta_VerticalAngle_Max
GoodSunVerticalAngleB_2 = finalwithsun_df['AngleBDelta'] > 0
GoodSunVerticalAngleB = GoodSunVerticalAngleB_1 & GoodSunVerticalAngleB_2

#GoodSunVerticalAngleB

GoodSunVerticalAngle = GoodSunVerticalAngleA | GoodSunVerticalAngleB
#GoodSunVerticalAngle

In [ ]:
#Now filter the dataframe with the two queries
finalwithsun_filtered_df = finalwithsun_df[GoodSunHorizontalAngle & GoodSunVerticalAngle]

# went from 6000+ rows to
print (r"Filtered large pandas dataframe  ok.")
print (r"Number of glare road segments = " + str(len(finalwithsun_filtered_df)))
finalwithsun_filtered_df

In [ ]:
# create the feature class output called output_roadsfc_calc
#finalwithsun_df.spatial.to_featureclass(input_fgdb,"roadsfc_calc",overwrite=True) 

finalwithsun_filtered_df.spatial.to_featureclass(output_roadsfc_calc) # output_roadsfc_calc

In [ ]:
# DONE
print (r"Outputed featureclass " + output_roadsfc_calc + " ok.")